FILE=linear_algebra.tex
BIBFILE=linear_algebra
INDEXFILE=linear_algebra
TEX=pdflatex
BIBTEX=bibtex
MAKEINDEX=makeindex

all: vc.tex bib index pdf

bib: $(FILE)
	$(TEX) $(FILE)
	$(BIBTEX) $(BIBFILE)

index: $(FILE)
	$(TEX) $(FILE)
	$(MAKEINDEX) $(INDEXFILE)

pdf: $(FILE)
	$(TEX) $(FILE)
	$(TEX) $(FILE)

clean: 
	rm -rf *.aux *.log *~ *.out *.toc *.idx *.ilg *.ind *.bbl *.bcf *.blg *.ptc *.xml */*.aux */*.log */*~ *.pdf vc.tex

vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\
		\\GITAbrHash{%h}\
		\\GITAuthorDate{%ad}\
		\\GITAuthorName{%an}" >> vc.tex
