FILE=linear_algebra.tex
BIBFILE=linear_algebra
INDEXFILE=linear_algebra
TEX=pdflatex
BIBTEX=bibtex
<<<<<<< HEAD
MAKEINDEX=makeindex

all: vc.tex bib index pdf
=======
INDEX=makeindex

all: vc.tex bib idx pdf
>>>>>>> d9e06e8f8e10477b8fc42ecfcb6ff32547875147

bib: $(FILE)
	$(TEX) $(FILE)
	$(BIBTEX) $(BIBFILE)
<<<<<<< HEAD

index: $(FILE)
	$(TEX) $(FILE)
	$(MAKEINDEX) $(INDEXFILE)

=======
idx: $(FILE)
	$(INDEX) $(BIBFILE)
>>>>>>> d9e06e8f8e10477b8fc42ecfcb6ff32547875147
pdf: $(FILE)
	$(TEX) $(FILE)
	$(TEX) $(FILE)

clean: 
	rm -rf *.aux *.log *~ *.out *.toc *.idx *.ilg *.ind *.bbl *.bcf *.blg *.ptc *.xml */*.aux */*.log */*~ *.pdf vc.tex

vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\
		\\GITAbrHash{%h}\
		\\GITAuthorDate{%ad}\
		\\GITAuthorName{%an}" >> vc.tex
